---
title: "Project5_BF528"
author: "adeengar"
date: "5/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PROGRAMMER

```{r installing packages}
#BiocManager::install('affy')
#BiocManager::install('affyPLM')
#BiocManager::install('sva')
#BiocManager::install('AnnotationDbi')
#BiocManager::install('hgu133plus2.db')
```

```{r loading packages}
library("affy")
library("affyPLM")
library("sva")
library("AnnotationDbi")
library("hgu133plus2.db")
packageVersion("gplots")

```


##read the array and normalise it

```{r normalisation}
dir_cels='/projectnb/bf528/users/group4/project1/samples'
affy_data = ReadAffy(celfile.path=dir_cels)
View(affy_data)
norm_arry <- rma(affy_data)

#get information from normalised array
getClass(affy_data)
```

##Relative Log Expression (RLE) and Normalized Unscaled Standard Error (NUSE) scores of the microarray samples

```{r analysis}
#RLE 
my_plm<- fitPLM(affy_data,normalize = T, background = T)
sta_rle=RLE(my_plm,type="stats")

#transfer from atom vector to matrix
dim(sta_rle)
dim(sta_rle) <- c(2,134)
my_med=sta_rle[1,]

#plot the histogram
hist_rle=hist(my_med)

#NUSE
sta_nuse=NUSE(my_plm,type="stats")
dim(sta_nuse)
dim(sta_nuse) <- c(2,134)
my_med_nuse=sta_nuse[1,]
hist_nuse=hist(my_med_nuse)
```

##correct for batch effects

```{r analysis}
library(readr)
proj_metadata=read_csv("/project/bf528/project_1/doc/proj_metadata.csv")
norm_matrix=exprs(norm_arry)
head.matrix(norm_matrix)
write.csv(norm_matrix,'norm.csv')
norm <- read_csv("norm.csv")
head(norm)
```

```{r analysis}
model <- model.matrix(~normalizationcombatmod, data = proj_metadata)
combat_norm_matrix <- ComBat(dat = norm_matrix, batch = proj_metadata$normalizationcombatbatch, mod = model)
write.csv(combat_norm_matrix,'combat_norm.csv')
combat_norm <- read_csv("combat_norm.csv")
transed_data=t(combat_norm_matrix)
transed_scale=scale(transed_data, center=T,scale=T)
scaled_data=t(transed_scale)
prcomp_data=prcomp(scaled_data,scale=F,center = F)
prcomp_data$rotation
pca_plot=plot(prcomp_data$rotation[,1:2])

#Threshold 1 used to concentrate the scaled_data

d2=scaled_data[-which(scaled_data<1),]
prcomp_d2=prcomp(d2,scale=F,center = F)
plot(prcomp_d2$rotation[,1:2])
```

## ANALYST

```{r analysis}
library("gplots")
check_expression <- function(row) {           
	samples <- 0
	for (col in 1:length(row)) {
    #Count samples for each gene above the threshold value
		if (row[col] > log2(15)) {
			samples <- samples + 1
		}
	}
	#For 20% of values above log2(15)
	return ((samples / length(row)) > 0.2)
}

check_variance <- function(row,median_sd) {
	df <- length(row) - 1
	testchi = df*(sd(row)/(median_sd))^2
	chiupper = qchisq((0.99)/2, df, lower.tail = FALSE)
	return (testchi > chiupper)
}

separate <- function(clustdata, filterdata, genenum, num) {
	newmatrix <- matrix(,genenum,0)
	for (x in 1:numsamples) {
		if (clustdata[x] == num) {
			newmatrix <- cbind(newmatrix,filterdata[x])
		}
	}
	return (newmatrix)
}

get_subtypes <- function() {
	colors <- c()
	for (x in 1:numsamples) {
		if (annomatrix[x] == "C3") {
			colors <- c(colors,"red")
		}
		else {
			colors <- c(colors,"blue")
		}
	}
	return (colors)
}

run_t_test <- function() {
	for (x in 1:numgenes) {
		t.test(cluster1[x,],cluster2[x,])
	}
}

read_gedata <- read.csv("/projectnb/bf528/users/group4/project1/code/combat_csv",sep=",")
gedata <- read_gedata[,-1]
rownames(gedata) <- read_gedata[,1]
read_annomatrix <- read.csv("/project/bf528/project_1/doc/proj_metadata.csv")	
annomatrix = read_annomatrix$cit.coloncancermolecularsubtype
filter1 <- apply(gedata,1,function(x) check_expression(x))
express <- gedata[filter1,]
median_sd <- median(apply(gedata,1,function(x) sd(x)))
filter2 <- apply(express,1,function(x) check_variance(x,median_sd))
variance <-express[filter2,]
filter3 <- apply(variance,1,function(x) (sd(x)/mean(x)) > 0.186)
covar <- variance[filter3,] #Gene expression data, fully-filtered
write.csv(covar,"filtered_gedata.csv")
numgenes = nrow(covar)
numsamples = ncol(covar)

#Heatmap construction

distdata <- dist(t(covar))		
dendrogram <- hclust(distdata,method="complete")
clusters <- cutree(dendrogram, k=2)
cluster1 <- separate(clusters,covar,numgenes,1)
cluster2 <- separate(clusters,covar,numgenes,2)
heatmap.2(as.matrix(covar),ColSideColors = get_subtypes(),xlab="Patient tumor samples",ylab= "Microarray probesets", labRow=c(""), labCol=c(""), tracecol="white") 
tstatistics <- unlist(lapply(1:numgenes, function(x)

#Welsch t test
  
t.test(cluster1[x,],cluster2[x,])$statistic))
pvalues <- unlist(lapply(1:numgenes, function(x) t.test(cluster1[x,],cluster2[x,])$p.value))
diffexpress <- data.frame(ID = rownames(covar), t_statistic = tstatistics, p_value = pvalues, adjusted_p_value = p.adjust(pvalues,"fdr"))
write.csv(diffexpress,"tttest.csv")
sigfilter <- diffexpress$adjusted_p_value < 0.05
siggenes <- diffexpress[sigfilter,]
sortedgenes <- siggenes[order(siggenes$adjusted_p_value),]
negfilter <- sortedgenes$t_statistic<0
negatives <-  sortedgenes[negfilter,]
sortednegs <-  negatives[order(negatives$adjusted_p_value),]


#write data to csv for biological analysis
varfilter <- apply(gedata,1,function(x) check_variance(x,median_sd))
varonly <- gedata[varfilter,]
write.csv(varonly,"var_filtered.csv")
var_numgenes = nrow(varonly)
var_distdata <- dist(t(varonly))		
var_dendrogram <- hclust(var_distdata,method="complete")
var_clusters <- cutree(var_dendrogram, k=2)
var_cluster1 <- separate(var_clusters,varonly,var_numgenes,1)
var_cluster2 <- separate(var_clusters,varonly,var_numgenes,2)
var_tstatistics <- unlist(lapply(1:var_numgenes, function(x) t.test(var_cluster1[x,],var_cluster2[x,])$statistic))
var_pvalues <- unlist(lapply(1:var_numgenes, function(x) t.test(var_cluster1[x,],var_cluster2[x,])$p.value))
var_diffexpress <- data.frame(ID = rownames(varonly), t_statistic = var_tstatistics, p_value = var_pvalues, adjusted_p_value = p.adjust(var_pvalues,"fdr"))
write.csv(var_diffexpress,"var_ttest.csv")
```

